version: 2
jobs:
  build:
    working_directory: ~/support-be
    
    docker:
      - image: circleci/node:15
    steps:
      - checkout
      - run:
          command: yarn install
          name: Install Dependencies
      - restore_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}
      - save_cache:
          key: npm-cache-v1-{{ checksum "yarn.lock" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: yarn test
